version: "3.2"

services:
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

  merchant-alerting:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      ENVIRONMENT: local
      VERSION: local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password