server:
    port: 8080
    servlet:
        contextPath: ${CONTEXT_PATH}
    forward-headers-strategy: FRAMEWORK

thd-identity:
    resource-server:
        enabled: true

        public-paths:
            - "/actuator/**"
            - "/api-docs/**"
            - "/swagger-ui.html"
            - "/swagger-ui/**"
            - "/"

        allowed-issuers:
            - pingfed-qa
            - azuread-qa
        authority-mappings:
            - issuer-name: pingfed-qa
              audience: spiffe://homedepot.dev/mpulse-ws
              authorities:
                  - ROLE_read
            - issuer-name: azuread-qa
              audience: spiffe://homedepot.dev/mpulse-ws
              authorities:
                  - ROLE_read
            - issuer-name: pingfed-qa
              audience: spiffe://homedepot.dev/mpulse-ui
              authorities:
                  - ROLE_read
            - issuer-name: azuread-qa
              audience: spiffe://homedepot.dev/mpulse-ui
              authorities:
                  - ROLE_read
            - issuer-name: pingfed-qa
              audience: spiffe://homedepot.dev/myassortment-service
              authorities:
                - ROLE_read
            - issuer-name: azuread-qa
              audience: spiffe://homedepot.dev/myassortment-service
              authorities:
                - ROLE_read

        path-checks:
            - path: /**
              needed-authorities:
                  - ROLE_read
