server:
  port: 8080

# Swagger config
springdoc:
  api-docs:
    path: /api-docs

# Logging config
logging:
  level:
    org:
      springframework: INFO

thd-identity:
  resource-server:
    enabled: false

    public-paths:
      - "/actuator/**"
      - "/api-docs/**"
      - "/swagger-ui.html"
      - "/swagger-ui/**"
      - "/matrix-client/**"
      - "/"

    allowed-issuers:
      - pingfed-qa
      - azuread-qa
    authority-mappings:
      - issuer-name: pingfed-qa
        audience: spiffe://homedepot.dev/mpulse-ws
        authorities:
          - ROLE_read
      - issuer-name: azuread-qa
        audience: spiffe://homedepot.dev/mpulse-ws
        authorities:
          - ROLE_read
      - issuer-name: pingfed-qa
        audience: spiffe://homedepot.dev/mpulse-ui
        authorities:
          - ROLE_read
      - issuer-name: azuread-qa
        audience: spiffe://homedepot.dev/mpulse-ui
        authorities:
          - ROLE_read
      - issuer-name: pingfed-qa
        audience: spiffe://homedepot.dev/myassortment-service
        authorities:
          - ROLE_read
      - issuer-name: azuread-qa
        audience: spiffe://homedepot.dev/myassortment-service
        authorities:
          - ROLE_read

    path-checks:
      - path: /**
        needed-authorities:
          - ROLE_read

spring:
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  datasource:
    url: jdbc:postgresql://${PSQL_HOST:0.0.0.0}:${PSQL_PORT:5432}/mpulse
    username: ${PSQL_USER}
    password: ${PSQL_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

respMatrixClientUrl: https://merch-product-resp-matrix-service.hd-merch-dev.gcp.homedepot.com/RespMatrix/rs

projectId: hd-merch-dev

