spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/mpulse
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2dll:
          create_namespaces: true
    show-sql: true