server:
  port: 8080

# Swagger config
springdoc:
  api-docs:
    path: /api-docs

# Logging config
logging:
  level:
    org:
      springframework: INFO

#THD Proxy Properties
thd-proxy-enabled: false
thd-proxy-host: thd-svr-proxy-qa.homedepot.com
thd-proxy-port: 7070
allow-mwg: false
thd-proxy-schema: http


thd-identity:
  resource-server:
    enabled: true

    public-paths:
      - "/actuator/**"
      - "/api-docs/**"
      - "/swagger-ui.html"
      - "/swagger-ui/**"
      - "/"

    allowed-issuers:
      - pingfed-qa
      - azuread-qa
    authority-mappings:
      - issuer-name: pingfed-qa
        audience: spiffe://homedepot.dev/mpulse-ws
        authorities:
          - ROLE_read
      - issuer-name: azuread-qa
        audience: spiffe://homedepot.dev/mpulse-ws
        authorities:
          - ROLE_read
      - issuer-name: pingfed-qa
        audience: spiffe://homedepot.dev/mpulse-ui
        authorities:
          - ROLE_read
      - issuer-name: azuread-qa
        audience: spiffe://homedepot.dev/mpulse-ui
        authorities:
          - ROLE_read

    path-checks:
      - path: /**
        needed-authorities:
          - ROLE_read